# Generated by Django 4.2.3 on 2023-07-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_alter_authors_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='biography',
            field=models.TextField(blank=True, help_text='Give more information about this author.', null=True, verbose_name='Authors biography'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Authors name'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='number_of_books',
            field=models.PositiveIntegerField(help_text='How many books have been pupblished by this author?', verbose_name='Number of Books'),
        ),
    ]
