# Generated by Django 4.2.3 on 2023-07-11 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_alter_authors_biography_alter_authors_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author',
        ),
    ]
