# Generated by Django 4.2.3 on 2023-07-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_rename_authors_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='author',
            name='number_of_books',
        ),
    ]
