# Generated by Django 4.2.3 on 2023-07-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authors", "0007_alter_author_options_remove_author_date_published_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
