# Generated by Django 4.2.3 on 2023-07-10 14:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Book Title")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Give more information about this book.",
                        null=True,
                        verbose_name="Book Description",
                    ),
                ),
                (
                    "date_published",
                    models.DateField(
                        help_text="When was this book published?",
                        verbose_name="Date of Publication",
                    ),
                ),
                (
                    "number_of_pages",
                    models.PositiveIntegerField(
                        help_text="How many pages does this book have?",
                        verbose_name="Number of Pages",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
