# Generated by Django 4.2.3 on 2023-07-11 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0007_alter_author_options_remove_author_date_published_and_more'),
        ('books', '0002_alter_book_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='authors.author'),
            preserve_default=False,
        ),
    ]
